using BookKeeping.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookKeeping.Repo.EntityConfigurations;

    public class AddressConfiguration : IEntityTypeConfiguration<Address>
{
    public void Configure(EntityTypeBuilder<Address> modelBuilder)
    {
        //Primary Key
        modelBuilder.
            HasKey(a => a.Identity);

        modelBuilder
            .Property(a => a.Identity)
        //Identity value is generated by the database if not specified
        //If specified then no database value is generated
            .ValueGeneratedOnAdd();

        modelBuilder
            .Property(a => a.City)
            .IsRequired()
            .HasMaxLength(255);

        modelBuilder
            .Property(a => a.Street)
            //Property is NOT NULL
            .IsRequired()
            .HasMaxLength(255);

        modelBuilder
            .Property(a => a.Number)
            .IsRequired()
            .HasMaxLength(255);

        // Unique compound constraint
        modelBuilder
            .HasIndex(a => new { a.Identity, a.City, a.Street, a.Number })
            .IsUnique();
    }
}