using BookKeeping.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookKeeping.Repo.EntityConfigurations;

public class AuthorConfiguration : IEntityTypeConfiguration<Author>
{
    public void Configure(EntityTypeBuilder<Author> modelBuilder)
    {
        //Primary Key
        modelBuilder.
            HasKey(a => a.Identity);

        //modelBuilder
        //    .Property(a => a.Identity)
        //    //Identity value is generated by the database if not specified
        //    //If specified then no database value is generated
        //    .ValueGeneratedOnAdd();

        modelBuilder
            .Property(b => b.Identity)
            //Specifies that the database should not automatically generate values for the property
            .ValueGeneratedNever();

        modelBuilder
            .Property(a => a.FirstName)
            .HasMaxLength(255);

        modelBuilder
            .Property(a => a.LastName)
            //Property is NOT NULL
            .IsRequired()
            .HasMaxLength(255);

        modelBuilder
            .Property(a => a.Nationality)
            .HasMaxLength(255);

        //Set this to test Author->DeleteAndUnlinkFullCascadeHandler
        //https://www.learnentityframeworkcore.com/relationships/referential-constraint-action-options
        //modelBuilder
        //    .HasMany(a => a.Addresses)
        //    .WithOne(a=> a.Author)
        //    .OnDelete(DeleteBehavior.SetNull);
    }
}
