using BookKeeping.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookKeeping.Repo.EntityConfigurations;

public class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> modelBuilder)
    {
        //Primary Key
        modelBuilder.HasKey(c => c.Identity);

        modelBuilder
            .Property(c => c.Identity)
            //Identity value is generated by the database if not specified
            //If specified then no database value is generated
            .ValueGeneratedOnAdd();

        modelBuilder
            .OwnsOne(
                customer => customer.ContactAndPayment,
                ownedNavigationBuilder =>
                {
                    ownedNavigationBuilder.ToJson();

                    ownedNavigationBuilder
                        .OwnsOne(
                            contactDetails => contactDetails.BankDetails,
                            bankDetails =>
                            {
                                bankDetails.OwnsMany(
                                    b => b.CreditCards,
                                    creditCard =>
                                    {
                                        //creditCard.WithOwner().HasForeignKey("OwnerId");
                                        //creditCard.Property<int>("Id");
                                        //creditCard.HasKey("Id");
                                    });
                            });
                });
    }
}