using BookKeeping.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookKeeping.Repo.EntityConfigurations;

public class EditorConfiguration : IEntityTypeConfiguration<Editor>
{
    public void Configure(EntityTypeBuilder<Editor> modelBuilder)
    {
        //Primary Key
        modelBuilder.
            HasKey(a => a.Identity);

        modelBuilder
            .Property(a => a.Identity)
            //Identity value is generated by the database if not specified
            //If specified then no database value is generated
            .ValueGeneratedOnAdd();

        modelBuilder
            .Property(a => a.FirstName)
            .HasMaxLength(255);

        modelBuilder
            .Property(a => a.LastName)
            //Property is NOT NULL
            .IsRequired()
            .HasMaxLength(255);

        modelBuilder.HasData(
            new Editor
            {
                Identity = Guid.NewGuid(),
                FirstName = "John",
                LastName = "Doe"
            });
    }
}