using BookKeeping.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookKeeping.Repo.EntityConfigurations
{
    public class LoanConfiguration : IEntityTypeConfiguration<Loan>
    {
        public void Configure(EntityTypeBuilder<Loan> modelBuilder)
        {
            //Primary Key
            modelBuilder.
                HasKey(a => a.Identity);

            modelBuilder
                .Property(a => a.Identity)
                //Identity value is generated by the database if not specified
                //If specified then no database value is generated
                .ValueGeneratedOnAdd();

            modelBuilder.ToTable("Loans", l => l.IsTemporal());
        }
    }
}
