version: "3.9" 
services:
  mongodb:                       
    container_name: mongodb      
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=MySecureStrongPassword1234
    ports:                        
      - "27017:27017/tcp"                                  
    networks:                
      netdb:
        ipv4_address: 10.0.10.2
    volumes:
      - mongodb_data:/data/db
  mssqldb:
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MySecureStrongPassword1234
    ports:                        
      - "1433:1433/tcp"
    networks:                
      netdb:
        ipv4_address: 10.0.10.3
    volumes:
      - mssqldb_data:/var/opt/mssql/data 
networks:
  netdb:
    name: netdb
    ipam:
      driver: default
      config:
        - subnet: "10.0.10.0/24"
          ip_range: "10.0.10.0/24"
          gateway: 10.0.10.1
volumes:
  mongodb_data:
  mssqldb_data: