using BookKeeping.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookKeeping.Repo.EntityConfigurations;

public class WritingConfiguration : IEntityTypeConfiguration<Writing>
{
    public void Configure(EntityTypeBuilder<Writing> modelBuilder)
    {
        //Primary Key
        modelBuilder.
            HasKey(a => a.Identity);

        modelBuilder
            .Property(a => a.Identity)
            //Identity value is generated by the database if not specified
            //If specified then no database value is generated
            .ValueGeneratedOnAdd();

        /*
         * Table per concrete type
         * Tables will be made only for NewsArticle, Ad and JobOffer
         * No table is added for base class.
         */
        modelBuilder.UseTpcMappingStrategy();

        /*
         * Table per type
         * Tables will be made for the base class Writing, NewsArticle, Ad and JobOffer
         * Table will be made for the base type
         */
        //modelBuilder.UseTptMappingStrategy();
    }
}